services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
