# Generated by Django 5.1.1 on 2024-10-13 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knowledge_level', models.IntegerField(choices=[(1, 'Well Known'), (2, 'Somewhat Known'), (3, 'Not Known')])),
                ('studied_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='core.flashcard')),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_studies', to='core.studysession')),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.studysession'),
        ),
    ]
